version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: markabot
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USERNAME}"]
      interval: 10s
      retries: 5

  adminer:
    image: adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  bot:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_VERSION: ${BOT_VERSION:-0.1.0}
      DB_URL: jdbc:postgresql://db:5432/markabot
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  db-data: